host: 127.0.0.1
port: 9500

# Length of time to keep an IP in cache (default 10800s or 3h)
cache_expiry: 10800

geolookup:
  service_url: https://get.geojs.io/v1/ip/geo/

redis:
  enabled: True
  host: 127.0.0.1
  port: 6379
  db: 0
  # Currently not suported
  #password: ""

logging:
  formatters:
    form01:
      format: "%(asctime)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      style: "%"
      validate: True
      class: logging.Formatter
  handlers:
    console:
      class: logging.StreamHandler
      level: NOTSET
      formatter: form01
      stream: ext://sys.stdout
  root:
    level: WARN
    handlers: [console]